use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DeviceDetails {
    pub serial: String,
    pub hardware_serial: String,
    pub adb_target: String,
    pub model: String,
    pub manufacturer: String,
    pub brand: String,
    pub device_name: String,
    pub android_version: String,
    pub sdk_level: String,
    pub build_id: String,
    pub build_fingerprint: String,
    pub security_patch: String,
    pub bootloader_state: String,
    pub build_type: String,
    pub cpu_abi: String,
    pub supported_abis: String,
    pub architecture: String,
    pub kernel_version: String,
    pub hostname: String,
    pub device_uptime: String,
    pub usb_state: String,
    pub adb_state: String,
    pub usb_debugging: String,
    pub wifi_debugging: String,
    pub root_availability: String,
    pub selinux_status: String,
    pub network_operator: String,
    pub sim_operator: String,
    pub sim_state: String,
    pub is_roaming: String,
    pub sim_country: String,
    pub operator_numeric: String,
    pub multisim_config: String,
    pub phone_number: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DeviceHealth {
    pub battery_level: u32,
    pub battery_temp: f32,
    pub battery_status: String,
    pub ram_total_mb: u64,
    pub ram_used_mb: u64,
    pub ram_usage_percent: f32,
    pub storage_total_gb: f32,
    pub storage_used_gb: f32,
    pub storage_usage_percent: f32,
    pub cpu_usage_percent: f32,
    pub network_type: String,
    pub adb_status: String,
    pub uptime_formatted: String,
}
