import {
  Power,
  Sun,
  Moon,
  Volume2,
  Volume1,
  VolumeX,
  Play,
  SkipForward,
  SkipBack,
  Camera,
  RotateCw,
  Globe,
  Bell,
  Lock,
  Unlock,
  Sliders,
  Home,
  ArrowLeft,
  Square,
  Sparkles,
} from "lucide-react";
import { QuickAction } from "./types";

export const QUICK_ACTIONS_REGISTRY: QuickAction[] = [
  // 1. Power & Display
  {
    id: "power_toggle",
    title: "Power Toggle",
    subtitle: "KEYEVENT_POWER (26)",
    category: "power_display",
    type: "keyevent",
    keycode: 26,
    icon: <Power className="h-6 w-6" />,
    btnVariant: "rose",
    commandSnippet: {
      title: "Power Button",
      command: (serial) => `adb -s ${serial} shell input keyevent 26`,
      description: "Toggles screen power state.",
    },
  },
  {
    id: "screen_wake",
    title: "Wake Screen",
    subtitle: "KEYCODE_WAKEUP (224)",
    category: "power_display",
    type: "keyevent",
    keycode: 224,
    icon: <Sun className="h-6 w-6" />,
    btnVariant: "amber",
    commandSnippet: {
      title: "Screen Wakeup",
      command: (serial) => `adb -s ${serial} shell input keyevent 224`,
      description: "Wakes up device display.",
    },
  },
  {
    id: "screen_sleep",
    title: "Sleep Screen",
    subtitle: "KEYCODE_SLEEP (223)",
    category: "power_display",
    type: "keyevent",
    keycode: 223,
    icon: <Moon className="h-6 w-6" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Screen Sleep",
      command: (serial) => `adb -s ${serial} shell input keyevent 223`,
      description: "Puts screen to sleep.",
    },
  },
  {
    id: "lock_screen",
    title: "Lock Screen",
    subtitle: "Turn Screen Off & Lock",
    category: "power_display",
    type: "custom_exec",
    icon: <Lock className="h-6 w-6" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Lock Screen",
      command: (serial) => `adb -s ${serial} shell input keyevent 26`,
      description: "Locks device display.",
    },
  },
  {
    id: "unlock_screen",
    title: "Unlock Device",
    subtitle: "Wake + Swipe Up to Unlock",
    category: "power_display",
    type: "custom_exec",
    icon: <Unlock className="h-6 w-6 text-emerald-400" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Unlock Screen",
      command: (serial) => `adb -s ${serial} shell input keyevent 224 && adb -s ${serial} shell input swipe 500 1500 500 500 200`,
      description: "Wakes screen and simulates swipe gesture to reveal pin/home.",
    },
  },
  {
    id: "rotate_screen",
    title: "Rotate Screen",
    subtitle: "Toggle Auto / Landscape",
    category: "power_display",
    type: "custom_exec",
    icon: <RotateCw className="h-6 w-6 text-cyan-400" />,
    btnVariant: "cyan",
    commandSnippet: {
      title: "Rotate Orientation",
      command: (serial) => `adb -s ${serial} shell settings put system accelerometer_rotation 1`,
      description: "Cycles through screen orientation and accelerometer states.",
    },
  },

  // 2. Audio & Media Controls
  {
    id: "volume_modal",
    title: "Multi-Stream Volume",
    subtitle: "Media, Call, Ring, Alarm",
    category: "audio_media",
    type: "dialog",
    icon: <Sliders className="h-6 w-6 text-cyan-400" />,
    btnVariant: "primary",
  },
  {
    id: "volume_up",
    title: "Volume Up",
    subtitle: "KEYCODE_VOLUME_UP (24)",
    category: "audio_media",
    type: "keyevent",
    keycode: 24,
    icon: <Volume2 className="h-6 w-6" />,
    btnVariant: "primary",
    commandSnippet: {
      title: "Volume Up",
      command: (serial) => `adb -s ${serial} shell input keyevent 24`,
      description: "Increments master audio volume.",
    },
  },
  {
    id: "volume_down",
    title: "Volume Down",
    subtitle: "KEYCODE_VOLUME_DOWN (25)",
    category: "audio_media",
    type: "keyevent",
    keycode: 25,
    icon: <Volume1 className="h-6 w-6" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Volume Down",
      command: (serial) => `adb -s ${serial} shell input keyevent 25`,
      description: "Decrements master audio volume.",
    },
  },
  {
    id: "volume_mute",
    title: "Mute Toggle",
    subtitle: "KEYCODE_VOLUME_MUTE (164)",
    category: "audio_media",
    type: "keyevent",
    keycode: 164,
    icon: <VolumeX className="h-6 w-6" />,
    btnVariant: "rose",
    commandSnippet: {
      title: "Toggle Mute",
      command: (serial) => `adb -s ${serial} shell input keyevent 164`,
      description: "Mutes or unmutes device audio.",
    },
  },
  {
    id: "media_play_pause",
    title: "Play / Pause",
    subtitle: "MEDIA_PLAY_PAUSE (85)",
    category: "audio_media",
    type: "keyevent",
    keycode: 85,
    icon: <Play className="h-6 w-6 text-emerald-400" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Play / Pause Media",
      command: (serial) => `adb -s ${serial} shell input keyevent 85`,
      description: "Toggles playback in active media app (Spotify, YouTube, Music).",
    },
  },
  {
    id: "media_next",
    title: "Next Track",
    subtitle: "MEDIA_NEXT (87)",
    category: "audio_media",
    type: "keyevent",
    keycode: 87,
    icon: <SkipForward className="h-6 w-6 text-cyan-400" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Next Track",
      command: (serial) => `adb -s ${serial} shell input keyevent 87`,
      description: "Skips to the next music/video track.",
    },
  },
  {
    id: "media_prev",
    title: "Previous Track",
    subtitle: "MEDIA_PREVIOUS (88)",
    category: "audio_media",
    type: "keyevent",
    keycode: 88,
    icon: <SkipBack className="h-6 w-6 text-cyan-400" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Previous Track",
      command: (serial) => `adb -s ${serial} shell input keyevent 88`,
      description: "Returns to previous music/video track.",
    },
  },

  // 3. Camera & Hardware Controls
  {
    id: "open_camera",
    title: "Open Camera",
    subtitle: "Launch Default Camera App",
    category: "camera_hardware",
    type: "custom_exec",
    icon: <Camera className="h-6 w-6 text-rose-400" />,
    btnVariant: "rose",
    commandSnippet: {
      title: "Open Camera App",
      command: (serial) => `adb -s ${serial} shell am start -a android.media.action.IMAGE_CAPTURE`,
      description: "Launches camera viewfinder directly on screen.",
    },
  },
  {
    id: "camera_shutter",
    title: "Camera Shutter",
    subtitle: "KEYCODE_CAMERA (27)",
    category: "camera_hardware",
    type: "keyevent",
    keycode: 27,
    icon: <Camera className="h-6 w-6 text-amber-400" />,
    btnVariant: "amber",
    commandSnippet: {
      title: "Trigger Camera Shutter",
      command: (serial) => `adb -s ${serial} shell input keyevent 27`,
      description: "Snaps a photo if camera viewfinder is open.",
    },
  },

  // 4. Navigation Keys
  {
    id: "nav_back",
    title: "Back Key",
    subtitle: "KEYCODE_BACK (4)",
    category: "navigation",
    type: "keyevent",
    keycode: 4,
    icon: <ArrowLeft className="h-6 w-6" />,
    btnVariant: "accent",
    commandSnippet: {
      title: "Back Button",
      command: (serial) => `adb -s ${serial} shell input keyevent 4`,
      description: "Simulates Android hardware back button.",
    },
  },
  {
    id: "nav_home",
    title: "Home Key",
    subtitle: "KEYCODE_HOME (3)",
    category: "navigation",
    type: "keyevent",
    keycode: 3,
    icon: <Home className="h-6 w-6" />,
    btnVariant: "primary",
    commandSnippet: {
      title: "Home Button",
      command: (serial) => `adb -s ${serial} shell input keyevent 3`,
      description: "Simulates Android home button.",
    },
  },
  {
    id: "nav_recents",
    title: "Recents / Switcher",
    subtitle: "KEYCODE_APP_SWITCH (187)",
    category: "navigation",
    type: "keyevent",
    keycode: 187,
    icon: <Square className="h-6 w-6" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Recents Button",
      command: (serial) => `adb -s ${serial} shell input keyevent 187`,
      description: "Opens app switcher multitasking carousel.",
    },
  },

  // 5. Shortcuts & Intent Dialogs
  {
    id: "open_url_dialog",
    title: "Open URL / Deep Link",
    subtitle: "Launch Browser / App Scheme",
    category: "shortcuts",
    type: "dialog",
    icon: <Globe className="h-6 w-6 text-cyan-400" />,
    btnVariant: "cyan",
  },
  {
    id: "custom_notification_dialog",
    title: "Custom Notification",
    subtitle: "Broadcast Custom Push Alert",
    category: "shortcuts",
    type: "dialog",
    icon: <Bell className="h-6 w-6 text-amber-400" />,
    btnVariant: "amber",
  },
  {
    id: "expand_notifications",
    title: "Expand Notifications",
    subtitle: "Pull Down Notification Shade",
    category: "shortcuts",
    type: "custom_exec",
    icon: <Sparkles className="h-6 w-6" />,
    btnVariant: "secondary",
    commandSnippet: {
      title: "Expand Status Bar",
      command: (serial) => `adb -s ${serial} shell cmd statusbar expand-notifications`,
      description: "Expands the notification shade on the phone.",
    },
  },
];
